# Sample workflow for building and deploying a Next.js site to GitHub Pages

name: Deploy Next.js site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Build and deploy job
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2  # Updated to v2
        with:
          fetch-depth: 0  # Fetch all history for proper deployment

      - name: Setup Node.js
        uses: actions/setup-node@v2  # Updated to v2
        with:
          node-version: "16"

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "yarn.lock" ]; then
            echo "manager=yarn"
            echo "command=install"
            echo "runner=yarn"
          elif [ -f "package-lock.json" ]; then
            echo "manager=npm"
            echo "command=ci"
            echo "runner=npm"
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Install dependencies
        run: ${{ steps.detect-package-manager.outputs.runner }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Build and Export with Next.js
        run: ${{ steps.detect-package-manager.outputs.runner }} next build && ${{ steps.detect-package-manager.outputs.runner }} next export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
